base:
  token: ideastop
  appid: wx4f48cdcea70e8805
  appsecret: 81c231d38a39c92564841e6ebf1d4ce9

api:
  # 获得 access_token
  access_token:
    scheme: https
    method: GET
    url: 'https://api.weixin.qq.com/cgi-bin/token'
  # 获得微信服务器IP列表
  callback_ip:
    scheme: https
    method: GET
    url: 'https://api.weixin.qq.com/cgi-bin/getcallbackip'
  # 上传多媒体文件
  upload_media:
    scheme: http
    method: POST
    url: 'http://file.api.weixin.qq.com/cgi-bin/media/upload'
  # 下载多媒体文件
  download_media:
    scheme: http
    method: GET
    url: 'http://file.api.weixin.qq.com/cgi-bin/media/get'